# This file contains a list of products with their attributes.
products_found = [
    {'id': 1, 'name': 'PixelMax X12', 'category': 'phone', 'price': 39386, 'storage_gb': 256, 'delivery_days': 1},
    {'id': 2, 'name': 'PixelMax Z12', 'category': 'phone', 'price': 80858, 'storage_gb': 64, 'delivery_days': 1},
    {'id': 3, 'name': 'Nova X4', 'category': 'phone', 'price': 70642, 'storage_gb': 128, 'delivery_days': 1},
    {'id': 4, 'name': 'Nimbus S12', 'category': 'phone', 'price': 36452, 'storage_gb': 512, 'delivery_days': 3},
    {'id': 5, 'name': 'Vertex X3', 'category': 'phone', 'price': 50829, 'storage_gb': 512, 'delivery_days': 1},
    {'id': 6, 'name': 'Orbit Pro2', 'category': 'phone', 'price': 55590, 'storage_gb': 64, 'delivery_days': 2},
    {'id': 7, 'name': 'Quanta Lite5', 'category': 'phone', 'price': 97567, 'storage_gb': 64, 'delivery_days': 3},
    {'id': 8, 'name': 'PixelMax Max2', 'category': 'phone', 'price': 109528, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 9, 'name': 'Quanta Lite4', 'category': 'phone', 'price': 15498, 'storage_gb': 64, 'delivery_days': 1},
    {'id': 10, 'name': 'Vertex X4', 'category': 'phone', 'price': 55614, 'storage_gb': 64, 'delivery_days': 2},
    {'id': 11, 'name': 'Quanta S6', 'category': 'phone', 'price': 35140, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 12, 'name': 'PixelMax Lite11', 'category': 'phone', 'price': 74096, 'storage_gb': 128, 'delivery_days': 1},
    {'id': 13, 'name': 'Zenith Max7', 'category': 'phone', 'price': 128742, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 14, 'name': 'Nimbus S11', 'category': 'phone', 'price': 111141, 'storage_gb': 256, 'delivery_days': 1},
    {'id': 15, 'name': 'Orbit X6', 'category': 'phone', 'price': 42128, 'storage_gb': 512, 'delivery_days': 1},
    {'id': 16, 'name': 'Halo Z6', 'category': 'phone', 'price': 88652, 'storage_gb': 128, 'delivery_days': 2},
    {'id': 17, 'name': 'Aster S5', 'category': 'phone', 'price': 39594, 'storage_gb': 128, 'delivery_days': 3},
    {'id': 18, 'name': 'Nimbus Pro12', 'category': 'phone', 'price': 117738, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 19, 'name': 'Quanta S3', 'category': 'phone', 'price': 20908, 'storage_gb': 512, 'delivery_days': 1},
    {'id': 20, 'name': 'PixelMax S11', 'category': 'phone', 'price': 105049, 'storage_gb': 128, 'delivery_days': 2},
    {'id': 21, 'name': 'Halo X7', 'category': 'phone', 'price': 81506, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 22, 'name': 'Nimbus Pro9', 'category': 'phone', 'price': 91633, 'storage_gb': 64, 'delivery_days': 1},
    {'id': 23, 'name': 'Nimbus Pro11', 'category': 'phone', 'price': 23385, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 24, 'name': 'Zenith Max1', 'category': 'phone', 'price': 126626, 'storage_gb': 256, 'delivery_days': 1},
    {'id': 25, 'name': 'Nimbus X11', 'category': 'phone', 'price': 110999, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 26, 'name': 'Halo S3', 'category': 'phone', 'price': 101500, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 27, 'name': 'Nimbus X10', 'category': 'phone', 'price': 68632, 'storage_gb': 256, 'delivery_days': 1},
    {'id': 28, 'name': 'Quanta Pro4', 'category': 'phone', 'price': 38904, 'storage_gb': 64, 'delivery_days': 3},
    {'id': 29, 'name': 'PixelMax X12', 'category': 'phone', 'price': 107922, 'storage_gb': 512, 'delivery_days': 3},
    {'id': 30, 'name': 'Zenith S11', 'category': 'phone', 'price': 123621, 'storage_gb': 512, 'delivery_days': 1},
    {'id': 31, 'name': 'CoreMax 16 G2', 'category': 'laptop', 'price': 106749, 'storage_gb': 1024, 'delivery_days': 5},
    {'id': 32, 'name': 'SwiftEdge 15 Elite', 'category': 'laptop', 'price': 96737, 'storage_gb': 1024, 'delivery_days': 3},
    {'id': 33, 'name': 'PrimeBook 13 G2', 'category': 'laptop', 'price': 41081, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 34, 'name': 'SwiftEdge 14 G1', 'category': 'laptop', 'price': 102244, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 35, 'name': 'SwiftEdge 13 G1', 'category': 'laptop', 'price': 41730, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 36, 'name': 'CoreMax 16 G2', 'category': 'laptop', 'price': 47569, 'storage_gb': 1024, 'delivery_days': 5},
    {'id': 37, 'name': 'PrimeBook 14 Elite', 'category': 'laptop', 'price': 53088, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 38, 'name': 'FlexNote 15 Elite', 'category': 'laptop', 'price': 79366, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 39, 'name': 'ProBook 13 G1', 'category': 'laptop', 'price': 104179, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 40, 'name': 'SwiftEdge 14 G2', 'category': 'laptop', 'price': 77617, 'storage_gb': 1024, 'delivery_days': 3},
    {'id': 41, 'name': 'TitanBook 15 Elite', 'category': 'laptop', 'price': 118075, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 42, 'name': 'PrimeBook 13 G1', 'category': 'laptop', 'price': 129931, 'storage_gb': 1024, 'delivery_days': 2},
    {'id': 43, 'name': 'AirLite 14 G2', 'category': 'laptop', 'price': 81135, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 44, 'name': 'FlexNote 13 G2', 'category': 'laptop', 'price': 35204, 'storage_gb': 512, 'delivery_days': 3},
    {'id': 45, 'name': 'CoreMax 16 G3', 'category': 'laptop', 'price': 101175, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 46, 'name': 'PrimeBook 14 G2', 'category': 'laptop', 'price': 55681, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 47, 'name': 'ProBook 15 G1', 'category': 'laptop', 'price': 90496, 'storage_gb': 256, 'delivery_days': 5},
    {'id': 48, 'name': 'TitanBook 13 Air', 'category': 'laptop', 'price': 115877, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 49, 'name': 'AirLite 14 Elite', 'category': 'laptop', 'price': 124451, 'storage_gb': 256, 'delivery_days': 5},
    {'id': 50, 'name': 'SwiftEdge 13 Air', 'category': 'laptop', 'price': 74825, 'storage_gb': 256, 'delivery_days': 5},
    {'id': 51, 'name': 'UltraBook 15 G2', 'category': 'laptop', 'price': 103037, 'storage_gb': 1024, 'delivery_days': 2},
    {'id': 52, 'name': 'CoreMax 16 G2', 'category': 'laptop', 'price': 96322, 'storage_gb': 1024, 'delivery_days': 3},
    {'id': 53, 'name': 'UltraBook 13 G1', 'category': 'laptop', 'price': 94009, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 54, 'name': 'AirLite 13 Air', 'category': 'laptop', 'price': 83058, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 55, 'name': 'UltraBook 13 G2', 'category': 'laptop', 'price': 62073, 'storage_gb': 512, 'delivery_days': 3},
    {'id': 56, 'name': 'VibeBuds Pro 3', 'category': 'audio', 'price': 21990, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 57, 'name': 'PulseAudio Buds 5', 'category': 'audio', 'price': 11528, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 58, 'name': 'SoundWave Max 3', 'category': 'audio', 'price': 5366, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 59, 'name': 'SonicPro Pro 2', 'category': 'audio', 'price': 10623, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 60, 'name': 'EchoPods Air 2', 'category': 'audio', 'price': 24530, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 61, 'name': 'PulseAudio One 3', 'category': 'audio', 'price': 31828, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 62, 'name': 'SoundWave One 3', 'category': 'audio', 'price': 2976, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 63, 'name': 'VibeBuds Max 3', 'category': 'audio', 'price': 6912, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 64, 'name': 'PulseAudio One 5', 'category': 'audio', 'price': 1823, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 65, 'name': 'SonicPro Max 5', 'category': 'audio', 'price': 2706, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 66, 'name': 'PulseAudio Pro 2', 'category': 'audio', 'price': 15897, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 67, 'name': 'BassCore Air 1', 'category': 'audio', 'price': 31613, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 68, 'name': 'SonicPro Max 1', 'category': 'audio', 'price': 13347, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 69, 'name': 'VibeBuds One 5', 'category': 'audio', 'price': 26606, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 70, 'name': 'VibeBuds Max 2', 'category': 'audio', 'price': 31026, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 71, 'name': 'EchoPods Air 4', 'category': 'audio', 'price': 28374, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 72, 'name': 'VibeBuds Max 3', 'category': 'audio', 'price': 6832, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 73, 'name': 'SoundWave One 1', 'category': 'audio', 'price': 30262, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 74, 'name': 'EchoPods One 3', 'category': 'audio', 'price': 11723, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 75, 'name': 'EchoPods Buds 2', 'category': 'audio', 'price': 14848, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 76, 'name': 'TabX 10 Plus', 'category': 'tablet', 'price': 72117, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 77, 'name': 'PadPro 8 Lite', 'category': 'tablet', 'price': 28534, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 78, 'name': 'TabX 8', 'category': 'tablet', 'price': 76382, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 79, 'name': 'FlexTab 12 Lite', 'category': 'tablet', 'price': 91256, 'storage_gb': 512, 'delivery_days': 2},
    {'id': 80, 'name': 'PadPro 8', 'category': 'tablet', 'price': 58232, 'storage_gb': 64, 'delivery_days': 5},
    {'id': 81, 'name': 'SlateMax 10', 'category': 'tablet', 'price': 95551, 'storage_gb': 64, 'delivery_days': 3},
    {'id': 82, 'name': 'ViewPad 10 Lite', 'category': 'tablet', 'price': 57119, 'storage_gb': 256, 'delivery_days': 5},
    {'id': 83, 'name': 'FlexTab 10', 'category': 'tablet', 'price': 61233, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 84, 'name': 'FlexTab 11 Pro', 'category': 'tablet', 'price': 48328, 'storage_gb': 256, 'delivery_days': 2},
    {'id': 85, 'name': 'PadPro 10 Pro', 'category': 'tablet', 'price': 81360, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 86, 'name': 'PadPro 11', 'category': 'tablet', 'price': 71779, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 87, 'name': 'FlexTab 9 Lite', 'category': 'tablet', 'price': 57843, 'storage_gb': 256, 'delivery_days': 5},
    {'id': 88, 'name': 'ViewPad 10 Lite', 'category': 'tablet', 'price': 71532, 'storage_gb': 128, 'delivery_days': 2},
    {'id': 89, 'name': 'SlateMax 9 Lite', 'category': 'tablet', 'price': 34300, 'storage_gb': 64, 'delivery_days': 3},
    {'id': 90, 'name': 'ViewPad 8', 'category': 'tablet', 'price': 90093, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 91, 'name': 'SlateMax 11', 'category': 'tablet', 'price': 34226, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 92, 'name': 'TabX 8', 'category': 'tablet', 'price': 28301, 'storage_gb': 128, 'delivery_days': 5},
    {'id': 93, 'name': 'ViewPad 11 Lite', 'category': 'tablet', 'price': 92819, 'storage_gb': 128, 'delivery_days': 2},
    {'id': 94, 'name': 'FlexTab 9', 'category': 'tablet', 'price': 95652, 'storage_gb': 256, 'delivery_days': 3},
    {'id': 95, 'name': 'ViewPad 12', 'category': 'tablet', 'price': 91056, 'storage_gb': 512, 'delivery_days': 5},
    {'id': 96, 'name': 'Stylus Pen Mini', 'category': 'accessory', 'price': 6915, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 97, 'name': 'Stylus Pen Elite', 'category': 'accessory', 'price': 4375, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 98, 'name': 'Bluetooth Speaker X1', 'category': 'accessory', 'price': 4336, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 99, 'name': 'Smartwatch Band Pro', 'category': 'accessory', 'price': 3746, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 100, 'name': 'Laptop Stand Max', 'category': 'accessory', 'price': 1483, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 101, 'name': 'Wireless Mouse Mini', 'category': 'accessory', 'price': 10500, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 102, 'name': 'Power Bank Mini', 'category': 'accessory', 'price': 6291, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 103, 'name': 'Screen Protector 200', 'category': 'accessory', 'price': 3339, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 104, 'name': 'Screen Protector Max', 'category': 'accessory', 'price': 14206, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 105, 'name': 'Stylus Pen Max', 'category': 'accessory', 'price': 5891, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 106, 'name': 'Laptop Stand Pro', 'category': 'accessory', 'price': 11375, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 107, 'name': 'Webcam Elite', 'category': 'accessory', 'price': 11098, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 108, 'name': 'Phone Case X1', 'category': 'accessory', 'price': 4311, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 109, 'name': 'Charger Mini', 'category': 'accessory', 'price': 5240, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 110, 'name': 'Smartwatch Band X1', 'category': 'accessory', 'price': 12654, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 111, 'name': 'Hub Adapter Max', 'category': 'accessory', 'price': 695, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 112, 'name': 'Hub Adapter Max', 'category': 'accessory', 'price': 10045, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 113, 'name': 'Bluetooth Speaker Mini', 'category': 'accessory', 'price': 2294, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 114, 'name': 'USB-C Cable 200', 'category': 'accessory', 'price': 4123, 'storage_gb': 0, 'delivery_days': 3},
    {'id': 115, 'name': 'Wireless Mouse Mini', 'category': 'accessory', 'price': 5104, 'storage_gb': 0, 'delivery_days': 5},
    {'id': 116, 'name': 'Mechanical Keyboard Mini', 'category': 'accessory', 'price': 4007, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 117, 'name': 'Phone Case 200', 'category': 'accessory', 'price': 11310, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 118, 'name': 'Laptop Stand X1', 'category': 'accessory', 'price': 9856, 'storage_gb': 0, 'delivery_days': 1},
    {'id': 119, 'name': 'Cooling Pad 200', 'category': 'accessory', 'price': 14258, 'storage_gb': 0, 'delivery_days': 2},
    {'id': 120, 'name': 'Stylus Pen 200', 'category': 'accessory', 'price': 9433, 'storage_gb': 0, 'delivery_days': 2},
]
